# Generated by Django 4.0 on 2022-08-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='указывать сумму в сомах', verbose_name='Цена'),
        ),
    ]
