# Generated by Django 4.0 on 2022-08-06 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_published_date_product_premier_product_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Процессор')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slug', models.SlugField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'Процессор',
                'verbose_name_plural': 'Процессоры',
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='пример для ввода "4GB/64GB"', max_length=50, verbose_name='Память')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slug', models.SlugField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'Память',
                'verbose_name_plural': 'Память',
            },
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Операционная система')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slug', models.SlugField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'Операционная система',
                'verbose_name_plural': 'Операционные системы',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='cpu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cpu', verbose_name='Процессор'),
        ),
        migrations.AlterField(
            model_name='product',
            name='memory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.memory', verbose_name='Память'),
        ),
        migrations.AlterField(
            model_name='product',
            name='operating_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.operatingsystem', verbose_name='Операционная система'),
        ),
    ]
