# Generated by Django 4.0 on 2022-08-19 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Заказанный продукт', 'verbose_name_plural': 'Заказанные продукты'},
        ),
    ]
